### ISSUE TITLE
Rotate gradients?

### ISSUE THREAD

**Issue by zocheyado** [Ghosh/uiGradients#104]
I am kind of a newbie when it comes to CSS Gradients, is it possible to rotate the gradients so that they go top to bottom instead of left to right?

**Comment by zocheyado** [comment]
Whoops! As I typed it I found the solution 
     background: -webkit-linear-gradient(90deg, #FF8008 10%, #FFC837 90%); /* Chrome 10+, Saf5.1+ */
Changing the initial rotation 90deg rotates the gradient!

**Comment by buschtoens** [comment]
[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient) is a great resource for all questions regarding CSS, JS and HTML. Should be useful for your future endeavors. :smiley: 

Also, you can markup code on GitHub with these ` back ticks. More information on Markdown [here](https://guides.github.com/features/mastering-markdown/).
