### ISSUE TITLE
Gradient Angle - Up and Down Arrow Keys

### ISSUE THREAD

**Issue by AustinPaquette** [ghosh/uiGradients#105]
The <kbd>up</kbd> and <kbd>down</kbd> arrow keys  could be utilized to modify the angle of which the gradient is angled at. (up arrow increases the deg value, while down naturally does the opposite).

**Comment by Ghosh** [comment]
@Murilirum Sorry for not replying earlier. I am planning on doing an update for the site. This is a good idea, I will probably include it in the next version. Thanks for the feedback.

**Comment by Murilirum** [comment]
Any time, I would have done a PR with the idea but I unfortunately didn't
(and still don't) have the time to jump on it but I think it would
certainly be useful. Potentially a sass mixin as well but I can admit
that's a bit of a stretch.

**Comment by Ghosh** [comment]
I agree, the sass mixin has been on my mind for a while, not really got around doing it. Also see #118, I think @SedueRey is attempting a library.

**Comment by SedueRey** [comment]
Yes, I'm looking for the best way to do it (Maybe a JS that converts every change of the library) or a gem.

**Comment by SedueRey** [comment]
Hello again, I've made and uploaded this https://github.com/SedueRey/uiGradientsSass .. Do you want me to keep it in a different repo? I would link this (of course) and keep it updated.

**Comment by Murilirum** [comment]
> Do you want me to keep it in a different repo

That depends, do you want to have the source of the main site based on SCSS as well or do you intend on that just being an additive? If it's going to power the site you can have SCSS in an `src` folder and then compile to a minified / standard compiled stylesheet in a `dist` folder for those who don't work with SCSS. My response to whether a secondary repo is needed or not grills down to what your goal is moving forward :laughing:

**Comment by SedueRey** [comment]
Well, my idea is just keep updated SCSS (I've just done this by now) and SASS, even LESS mixin and class library :D I don't mind if you prefer to keep it on another scope to keep out of uiGradient proposal, as a "plugin"

I mean, do you want me to update libraries when there is a PR or you prefer I do for my own? :)

**Comment by Ghosh** [comment]
@SedueRey Thank you for the library. I am perfectly fine if you wish to keep it in your repo. Also incase, you want to discuss further on this, please open a new issue :)

**Comment by alihossein** [comment]
:100:

**Comment by ghosh** [comment]
Released in 2.0
