### ISSUE TITLE
Is there a way to install UI Gradients as a gem

### ISSUE THREAD

**Issue by SedueRey** [Ghosh/uiGradients#118]
I am planning to use it on a project, I would want to know if there's a way to install this awesome gradient library inside a SASS project as a gem

This is just a question :)

**Comment by Ghosh** [comment]
@SedueRey Hi, unfortunately there is no way I know of where you can get is a gem. But that sounds like a good idea. It will be handy to provide all these gradients in a library of sorts.

**Comment by SedueRey** [comment]
I will take a look on how to do this, I don't ever knew how to program in Ruby but if it's necessary it could be great :D 

In JavaScript would be trivial so this, I will take a look

**Comment by Ghosh** [comment]
@SedueRey  Ok that is great. Maybe it would be easier if you just made a stand alone sass library and then make it available for distribution via a ruby gem. This way, it will be easier to add support for other channels too, like bower, npm etc. 

Do let me know if you need any help on this. I would love to help you out.

**Comment by SedueRey** [comment]
Yeah, it would be easier for me at all :D ... I'll tell you if I need anything.
