### ISSUE TITLE
Banding-ish issue

### ISSUE THREAD

**Issue by Wolfgange3311999** [Ghosh/uiGradients#147]
It looks as though the gradients — especially the grey to grey ones — have slightly colored bands as if there were dithering applied only horizontally. However, these bands are blurred across several pixels as if the gradient were rendered at a low resolution and then upscaled with a filter.

Either way, here's a screenshot of the issue (note that the bands can only be seen when the image is viewed 1:1 with the monitor):
![screenshot from 2016-05-15 20 15 00](https://cloud.githubusercontent.com/assets/5875019/15278178/85c763ea-1ada-11e6-9fc4-8b72a9b8c4c5.png)
And here is a progressing of colors from left to right that I found demonstrating that dithering in one direction already occurs:
#5e0302
#5d0302
#5e0402

**Comment by Ghosh** [comment]
@Wolfgange3311999 Thanks for bringing this up. However, this is not an issue with this project itself. To the best of my knowledge, the dithering and banding that you noticed happens on some browsers depending upon the os/graphic card etc. Not really sure if there is anything I can do from my end to solve this.

Closing this as it's not an issue with the project.
