### ISSUE TITLE
Add text-shadow to .infobox and/or footer

### ISSUE THREAD

**Issue by yanyi** [Ghosh/uiGradients#148]
![metallic_toad](https://cloud.githubusercontent.com/assets/234819/15891009/171c4400-2da5-11e6-9733-a4a6dab1cd52.png)

When an uploaded gradient has a light/white `Colour 2`, the `.infobox` text can't be read, and so are the text in the footer. Had to use <kbd>⌘</kbd>+<kbd>A</kbd> to highlight all the text on the page to see the values.

Would you consider adding text-shadow property?

**Comment by Ghosh** [comment]
Thanks for bringing this up. I knew about this but was procrastinating about fixing this. Didn't add a text shadow, but dynamically calculate the colour now. Fixed in b9542cd.

**Comment by yanyi** [comment]
Awesome. It's much better. Thank you!
