### ISSUE TITLE
How can you download these as images?

### ISSUE THREAD

**Issue by ili-codes** [Ghosh/uiGradients#151]

**Comment by shivarajnaidu** [comment]
Which images ?

**Comment by ili-codes** [comment]
How can I download the gradients as images?

**Comment by Ghosh** [comment]
@ili-codes Sorry, currently its not possible to download the gradients as images. I think your best option is to just take a screenshot or alternatively write a script using the `gradients.json` to programmatically generate the images.

Closing this issue for now. Feel free to comment if you need any other help.
