### ISSUE TITLE
Smarter JSON spec

### ISSUE THREAD

**Issue by buschtoens** [Ghosh/uiGradients#16]
First of all, thanks for this great repo.

---

In my opinion the JSON format should be changed. I propose the following:

```JSON
[
  {
    "name":   "Emerald Water",
    "colors": ["#348F50", "#56B4D3"]
  }
]
```

This uses the American spelling for the word "color", which is used by CSS. For the colors themselves, an array should be used instead of enumerated keys (`"colourN"`). This also allows for more than two colors per gradient.

I'd happily submit a PR for `master` and `site`. Let me hear, what you think.

**Comment by yasircs4** [comment]
[
  {
    "name":      "Soft Meat",
    "colors":    ["#e3a07c", "#e3c485"],
  }
]


  linear-gradient( 180deg, #e3a07c 0%, #e3c485 100%);

**Comment by zeusdeux** [comment]
[Here's](https://github.com/zeusdeux/colorfad.in/blob/master/data/animations.json) the structure I use at [colorfad.in](http://colorfad.in). The repo also contains scripts for validating the structure and thus making automated deploys a piece of cake.
