### ISSUE TITLE
Recently added Gradient Doesn't Work.

### ISSUE THREAD

**Issue by gowri-sankar** [ghosh/uiGradients#215]
Recently added gradient "Chitty Chitty Bang Bang" doesn't seem to work properly. Thumbnail is wrong and only a white blank page is rendered across several browsers.

Safari
<img width="1280" alt="screen shot 2017-03-09 at 10 21 20 pm" src="https://cloud.githubusercontent.com/assets/14316256/23760787/c384cd7c-0516-11e7-98b9-75fa5b2459b1.png">

Chrome
<img width="1280" alt="screen shot 2017-03-09 at 10 20 52 pm" src="https://cloud.githubusercontent.com/assets/14316256/23760789/c4646428-0516-11e7-91e8-673293757176.png">

Firefox
<img width="1280" alt="screen shot 2017-03-09 at 10 20 39 pm" src="https://cloud.githubusercontent.com/assets/14316256/23760788/c3fea6ba-0516-11e7-8120-cd96f09e9fe5.png">

**Comment by ghosh** [comment]
@gowri-sankar Thanks for the heads up. It's fixed now.
