### ISSUE TITLE
API for getting an random gradient from uiGradients?

### ISSUE THREAD

**Issue by mount2010** [ghosh/uiGradients#217]
This would help if you were lazy to get an background/ want your users to have different backgrounds every time.
Perhaps set up an API where developers can send XMLHttpRequests to receive an random CSS gradient in JSON form?

**Comment by ghosh** [comment]
@mount2010 Thanks for the suggestion. I have been thinking about this a while actually.

Problem is, this is a static site hosted on gh-pages. Not sure how it would be possible to provide this functionality with our current setup. 

There is a endpoint from where you could access all the gradients though - [http://uigradients.com/gradients.json](http://uigradients.com/gradients.json)

**Comment by ghosh** [comment]
Don't see how this is possible - best option is to use github data
```
https://raw.githubusercontent.com/ghosh/uiGradients/master/gradients.json
```

**Comment by prahubhatt** [comment]
Thank you very much! I will parse this JSON file and will be able to provide multiple themes for my Android app.

**Comment by LarryTheFatCat** [comment]
+1 
even though this is very old very beneficial allowing me to create a bg for my website's classroom's banners
