### ISSUE TITLE
Using gradients.json to populate data in my app

### ISSUE THREAD

**Issue by petrovicstefanrs** [ghosh/uiGradients#225]
I was wondering if using the json with gradients to populate the database for my app is ok. I wrote a little script in js that rips all gradients with two colors and writes them to my database. I put a notice on the page that most of the gradients were taken from uiGradients and also provided a link to the website, however i wanted to know if that is ok as i plan to use the script i wrote in admin panel for the app so i could at a later point fetch new gradients as they are added as well. If the creator of this repo doesn't give his permission for me to do this i will remove the feature from the app.
Note: gradient fetching is controlled, im not constantly scavenging the data on every pageload.
Other note: Sorry for my poor english! :D

**Comment by gregsonar** [comment]
uiGradients is really an excellent source of beautiful gradients and it would be cool to be able to enjoy them all the time in own pet projects.

I wonder if it's possible to implement the API to get a list of gradients, or it will be too heavy load?

**Comment by ghosh** [comment]
@petrovicstefanrs Thank you for asking. This project was built to help other people make stuff. You can use it in any way that you want. :smile:

@gregsonar Please feel free to go ahead and use it in our own project. While there is no api at the moment you can use this endpint to get a list of all gradients:-
```
https://raw.githubusercontent.com/ghosh/uiGradients/master/gradients.json
```

**Comment by petrovicstefanrs** [comment]
Thank you very much for the answer and the awesome project. Cheers! :D
