### ISSUE TITLE
Aubergine not showing color that shows in menu

### ISSUE THREAD

**Issue by janva255** [ghosh/uiGradients#255]
If you go to
https://uigradients.com/#Aubergine
The colors are this
#20002c
→ 
#cbb4d4
![screenshot_2](https://user-images.githubusercontent.com/13240448/26842054-defb9f90-4ac1-11e7-9d54-17534a5e19d1.jpg)

But in the show all gradients displays this
![screenshot_1](https://user-images.githubusercontent.com/13240448/26841988-a43ebaa4-4ac1-11e7-8c69-f4706daca1bc.jpg)

**Comment by dospunk** [comment]
I just checked and it's showing correctly for me. Maybe it was a one time bug?

**Comment by janva255** [comment]
@dospunk mmmm, keeps showing like this, also, loaded page again with shift+f5 to avoid cache and it shows the same
![screenshot_2](https://user-images.githubusercontent.com/13240448/26856884-1791a260-4afd-11e7-8aa0-4bb8b45c1213.jpg)
![screenshot_1](https://user-images.githubusercontent.com/13240448/26856885-17aeb2b0-4afd-11e7-8d50-8434f5f64476.jpg)

**Comment by dospunk** [comment]
Found the issue, there's two gradients named Aubergine

[here](https://github.com/ghosh/uiGradients/blob/master/gradients.json#L83) and [here](https://github.com/ghosh/uiGradients/blob/master/gradients.json#L870)

**Comment by ghosh** [comment]
Hey guys, thanks for bringing this up. @dospunk is correct, there was a duplicate value for `Aubergine`. Fixed in 668f7e8.
