### ISSUE TITLE
Get rgba code

### ISSUE THREAD

**Issue by janva255** [ghosh/uiGradients#257]
Any chance that you can add a rgba option?? to set the opacity of the colors, so you can copy the code with hex code or with rgba

**Comment by ghosh** [comment]
@janva255 Thanks for the suggestion. Unfortunately, at the moment there are no plans to include this feature. However, if there seems to be a lot of demand for it, I might add it in the future.

Meanwhile, you can just paste the copied color in google. It gives you a nice little color picker which automatically converts the color to RGBA.

**Comment by janva255** [comment]
@ghosh Yep! that's what i've been doing till now
