### ISSUE TITLE
How to build & run this website locally

### ISSUE THREAD

**Issue by seuplus** [ghosh/uiGradients#269]
Sir. uiGradients is a really great project. I like it very much. And the website [uigradients.com](https://uigradients.com) (using Vue) is very cool. How can I build & run it on my Mac locally or Linux server? Thank you!

**Comment by schmanat** [comment]
First clone the repo, and then run `npm install` After that you can use `npm start` to start the dev server. Ater that you can access the webapp at `localhost:9000`.

If you look at the `package.json` you see a lot of another commands to deploy or build the app.

**Comment by seuplus** [comment]
Thank you very much!

**Comment by seuplus** [comment]
Sir. Follow your guides, I succeed running the project on my Mac locally.

But it failed when I tried it on VPS (CentOS 7). 

![screen shot 2017-07-17 at 17 02 56](https://user-images.githubusercontent.com/26323968/28261478-0d013a74-6b12-11e7-962c-b9dddda68cc6.png)

![screen shot 2017-07-17 at 17 04 21](https://user-images.githubusercontent.com/26323968/28261481-0f0baaac-6b12-11e7-8282-23440bbc8b70.png)

Chrome Console:
![screen shot 2017-07-17 at 17 05 47 1](https://user-images.githubusercontent.com/26323968/28261636-9aa7a85e-6b12-11e7-9efd-6c0b792217c4.png)

I don't know where the `https://color.*****.com/app.js` is. Hope you can help me. Thank you.

**Comment by ghosh** [comment]
@seuplus Hey. Every time you build the project via `npm start` a `dist` folder is generated. Ideally, this is the folder you want to deploy and this is the folder to which your domain root should be pointing to.

Hope this clears things up. Closing this issue for now. Feel free to add any question you may have here.

**Comment by seuplus** [comment]
Thanks for your reply. Sir.

Worked now! I build the uiGradients project via `npm run build` and a `dist` folder is generated indeed.
