### ISSUE TITLE
I created a uiGradients iOS viewer application and published it to the app store!

### ISSUE THREAD

**Issue by thexande** [ghosh/uiGradients#282]
![device_mockup](https://user-images.githubusercontent.com/7704414/30000800-648b2cbc-9035-11e7-81b5-106540d8ed84.png)
![ui_gradients_viewer](https://user-images.githubusercontent.com/7704414/30000844-2b532100-9037-11e7-9276-a343796f2897.gif)

Greetings:

As an iOS Developer, I am always looking for new opportunities for cool projects. After using your web app, I decided to implement a gradient view swiper in swift. Additionally, I have published it to the app store for everyone to use. If you find the project neat, it would be great to add it to your list of resources under "built with uiGradients".

https://github.com/thexande/uiGradients-Viewer-iOS

Give the app a download, and check it out! Thanks for the inspiration.

**Comment by ghosh** [comment]
@thexande This is great! 👍 

Thanks for letting me know, I will definitely add it to the readme.
