### ISSUE TITLE
Copying colors is not working

### ISSUE THREAD

**Issue by BaptisteGelez** [ghosh/uiGradients#343]
I'm using Firefox 57 on GNU/Linux, and when I click on a color code to copy it, my the content of my clipboard doesn't change.

**Comment by schmanat** [comment]
is there any error on the js console?

**Comment by Bat41** [comment]
No. Actually, it's seems to work the second time I click it, but never the first time.

**Comment by ghosh** [comment]
@Bat41 Thank you for the heads up. It seems it's not working in chrome either.

**Comment by rfoel** [comment]
This could be fixed using Vuex.

**Comment by twistedpixel** [comment]
Can confirm this is also present in Safari and Safari Tech Preview (latest versions). Copies only on the second click.
