### ISSUE TITLE
Corrupt .jpg file when download the image

### ISSUE THREAD

**Issue by developerhuman12** [ghosh/uiGradients#372]
![screenshot from 2018-02-12 10-38-50](https://user-images.githubusercontent.com/15534661/36084203-06fb4ef2-0fe1-11e8-8905-8b82882c110b.png)

**Comment by foxdog05000** [comment]
This file is .png not .jpg

**Comment by developerhuman12** [comment]
At right side we have the option to download jpg and after download it's
not opening can you check screenshot.

**Comment by ghosh** [comment]
It seems to be working now. Closing this issue.

Feel free to re-open if the problem still exists.
