### ISSUE TITLE
Vue warn: Avoid using non-primitive value as key, use string/number value instead.

### ISSUE THREAD

**Issue by LiaoJimmy** [ghosh/uiGradients#382]
Hello, today I clone this repo. I `npm install` and `npm run dev`.
I see some Vue warning on my browser.
<img width="1280" alt="screen shot 2018-02-28 at 9 52 33 am" src="https://user-images.githubusercontent.com/11155585/36765803-f940a23c-1c6d-11e8-8a74-f314a3daa336.png">

It's also shown on my Visual Studio Code.
<img width="1280" alt="screen shot 2018-02-28 at 9 53 49 am" src="https://user-images.githubusercontent.com/11155585/36765819-094a26a8-1c6e-11e8-8a2f-f0b8be832c7a.png">

This warning is a little annoying,
so I'd like to try to fix this Vue.js key issue by myself.
It would be nice if you could provide some suggestions, Thanks.

**Comment by ghosh** [comment]
Fixed in another commit. Thank you.

**Comment by LiaoJimmy** [comment]
Got it.
