### ISSUE TITLE
Interfacing Library for gradients.json

### ISSUE THREAD

**Issue by Gabriel-Denys** [ghosh/uiGradients#564]
Hey all,
I know there is no API and I saw some people ask for it. 
I made the next best thing - a JS library that you can run in your project to select a random gradient based on a seed.

It might not suit all as I made it for a different project I was working on. Hopefully it saves people some time using uiGradients JSON in their own projects

check it out here [RandomGradient](https://github.com/Gabriel-Denys/RandomGradient)

**Comment by ghosh** [comment]
Thanks @Gabriel-Denys. Will add this to the README.
