### ISSUE TITLE
New Colors not appearing on website

### ISSUE THREAD

**Issue by chak217** [ghosh/uiGradients#628]
I added a color about 7 months ago called Bleem and it still hasn't appeared on the site.

**Comment by fz285** [comment]
Change the hotjar URL in index.html :  (window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');


Code -

 <script>
      (function(h,o,t,j,a,r){
          h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
          h._hjSettings={hjid:54906,hjsv:5};
          a=o.getElementsByTagName('head')[0];
          r=o.createElement('script');r.async=1;
          r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
          a.appendChild(r);
      })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>

**Comment by ghosh** [comment]
@chak217 I've been busy lately, not updated the site yet. Will do so soon.
