### ISSUE TITLE
Incorrect Hex getting copied on Martini & Behongo

### ISSUE THREAD

**Issue by Maddoxx88** [ghosh/uiGradients#693]
The one being displayed is #24fe41 but #ffffff is getting copied.

**Comment by Maddoxx88** [comment]
Behongo - #061700 getting copied as #ffffff

**Comment by p44v9n** [comment]
Have you tried this with a cleared clipboard? Can't replicate this bug, for me it copies the hex code correctly

**Comment by Maddoxx88** [comment]
Checked it, guess it might be a clipboard issue!
